### PR TITLE
Mention agent json_log in values.yaml.

### PR DESCRIPTION
**Pull request by meowjesty**
- Issue: [#494](https://github.com/metalbear-co/operator/issues/494)

From the issue:

@aviramha 

> When we do it probably would need to support podLabels and podAnnotations for the agent itself

I'm not quite sure what this means?

Also, options passed through `extraConfig` have to be snake case (match the agent config). It failed when I tried setting it to `jsonLog` like the operator value, as it works there due to `jsonLog` being converted into `true`/`false` in the helm thingy.

### CODE REVIEW

**Comment by aviramha** [comment]
Some of our users collect logs from pods based on annotations/labels (i.e collect-logs=true) and if we want them to be able to consume the agent logs the operator needs to support settings those annotations/labels.
It can also come as part of agent extra config. (but need to change the operator code to use that as well)

**Comment by meowjesty** [comment]
So I just make up something like this?

```yaml
podAnnotations: {
  operator_json_logs: true
  agent_json_logs: true
}
podLabels: {
  operator_json_logs: true
  agent_json_logs: true
}
```

**Comment by aviramha** [comment]
> So I just make up something like this?
> 
> ```yaml
> podAnnotations: {
>   operator_json_logs: true
>   agent_json_logs: true
> }
> podLabels: {
>   operator_json_logs: true
>   agent_json_logs: true
> }
> ```

No, the idea is that we let users supply their annotations/labels - see the labels/annotations we let users specify (on helm chart) for the operator deployment itself.

**Comment by meowjesty** [comment]
Ah, so it's like a user setting

```yaml
metadata:
  name: cat-pod
  labels:
    user: "mister-cat
```

And we want this to be passed to our agent spec:

```yaml
metadata:
  name: mirrord-agent
  labels:
    app: "agent"
    user: "mister-cat  <-- we insert it here
```

**Comment by aviramha** [comment]
yes

**Comment by meowjesty** [comment]
I think we have merged all the mirrord stuff needed.

**Comment by meowjesty** [comment]
Nope, still needs https://github.com/metalbear-co/operator/pull/530

**Comment by meowjesty** [comment]
Do we need to update any numbers here? This change is just docs, as `extraConfig` already takes everything you pass as args.

You would need to use an updated operator (unreleased actually).

**Review by aviramha — APPROVED** [review]

**Pull request merged**
